
#COLOR_RED   := $(shell tput setaf 1)
#COLOR_GREEN := $(shell tput setaf 2)
#COLOR_BLUE := $(shell tput setaf 4)
#COLOR_NONE  := $(shell tput sgr0)

#OLD_SHELL := $(SHELL)
#SHELL = $(info $(COLOR_BLUE))$(warning $(COLOR_RED)[$@]$(COLOR_NONE)  $(COLOR_GREEN)($^)$(COLOR_NONE))  $(OLD_SHELL) -x

NAME     := am
SRCS      = $(addprefix src/, $(AM_SRCS))
INC_PATH += $(AM_HOME)/am/src

include $(AM_HOME)/Makefile